apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: demo
spec:
  type: ClusterIP
  selector:
    app: identity-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
